### ISSUE TITLE
merchantReference doesn't allow uppercase letters

### ISSUE THREAD

**Issue by butaminas** [burnbright/omnipay-poli#12]
Any uppercase letters that are included in the `merchantReference` parameter are removed by preg\_replace.

Based on the official [docs](https://www.polipayments.com/InitiateTransaction), uppercases letters should be allowed.

**Comment by onlinesid** [comment]
@butaminas would you mind checking if the above fixes it? :)

**Comment by butaminas** [comment]
@onlinesid can confirm - it is working properly right now! Thanks.
