### ISSUE TITLE
Poli payments australia

### ISSUE THREAD

**Issue by pjebs** [burnbright/omnipay-poli#4]
Will this work with polioayments Australia? Ie with Australian endpoint?

**Comment by onlinesid** [comment]
Not at the moment, the end point is hard coded to the NZ one. Easy to change but I don't have a test account for POLi Australia. I'm going to ask my contact if I can get one but otherwise feel free to submit a pull request :)

**Comment by onlinesid** [comment]
Sorry, I was wrong there. The end point seems to be a global one, e.g.: https://poliapi.apac.paywithpoli.com/api/v2/Transaction/GetTransaction

So may be it might work with POLi Australia after all?

**Comment by pjebs** [comment]
Yes I realised. Unfortunately Laravel 5.2 simply doesn't work with the current version of OmniPay due to Omnipay using an outdated version of guzzle :-(

**Comment by onlinesid** [comment]
I see, I'm not familiar with Laravel, just let me know if there's anything I can do from this repo to help :)

**Comment by jedateach** [comment]
Worth a try, but it wasn't developed using an Australian account. Can't be
too difficult to make it work in both regions.

**Comment by onlinesid** [comment]
I inquired to POLi NZ about getting a POLi Australia test account for this and this was their response:

"An Australia test account is identical to the one you've already got.  The POLi infrastructure for Australia and NZ is all in one place.  The only difference is the bank list in Active mode.  iBank is identical."
