### ISSUE TITLE
Upgrade to API v2

### ISSUE THREAD

**Issue by jedateach** [burnbright/omnipay-poli#7]
The test API endpoint now returns a failure response along with a deprecation message.

V2 API docs can be found here: https://www.polipayments.com/APIintro

**Comment by jedateach** [comment]
Actually, I can see this is already part of master. I've been working on an older version :man_facepalming:

**Comment by jedateach** [comment]
I'll proceed to add this to a v1 branch

**Comment by onlinesid** [comment]
Should this be closed then?
